version: '3.8'

services:
  web:
    build: .
    command: gunicorn networknox.wsgi:application --bind 0.0.0.0:5001
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: networknox
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
